package com.example.demo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class FIRDetails {
    private String firNumber;
    private String policeStation;
    private Date firDate;
    private String remarks;

    // Getters and Setters are generated by Lombok

    /**
     * Provides a formatted string representation of the FIR details.
     *
     * @return A string containing the FIR details in a readable format.
     */
    @Override
    public String toString() {
        return "FIRDetails{" +
                "FIR Number='" + firNumber + '\'' +
                ", Police Station='" + policeStation + '\'' +
                ", FIR Date=" + (firDate != null ? firDate.toString() : "N/A") +
                ", Remarks='" + remarks + '\'' +
                '}';
    }

    /**
     * Validates the FIR details to ensure all required fields are populated.
     *
     * @return true if all required fields are valid, false otherwise.
     */
    public boolean validate() {
        if (firNumber == null || firNumber.isEmpty()) {
            return false;
        }
        if (policeStation == null || policeStation.isEmpty()) {
            return false;
        }
        if (firDate == null) {
            return false;
        }
        return true;
    }
}